name: repo_viewer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^4.2.0
  freezed_annotation: ^0.14.2
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0
  flutter_hooks: ^0.16.0
  hooks_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/hooks_riverpod
  webview_flutter: ^2.0.8
  flash: ^2.0.0
  auto_route: ^2.2.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  build_runner: ^2.0.4
  lint: ^1.5.3
  auto_route_generator: ^2.1.0
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/flutter_riverpod
  riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/riverpod
